/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.ListModel;
import javax.swing.text.DefaultEditorKit;

import org.alicebot.ab.MagicBooleans;
import org.alicebot.ab.TestAB;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Borys
 */
public class simpleGui extends javax.swing.JFrame {
    
    public ArrayList<URL> links;
    public ArrayList<URL> mediaLinks;
    private JList rowList;
    public BotMain bot;
    public static String[] args;
    /**
     * Creates new form simpleGui
     */
    public simpleGui() {
        initComponents();
        links = new ArrayList<>();
        mediaLinks = new ArrayList<>();
        JMenuBar bar = createMenuBar();
        workingPanel.add(bar,BorderLayout.BEFORE_FIRST_LINE);
        workingPanel.revalidate();
        workingPanel.repaint();
        String[] stringArray = {};
        rowList = new JList(stringArray);
        rowList.setVisibleRowCount(20);
        DefaultListModel model = new DefaultListModel();
        rowList.setModel(model);
        jScrollPane1.setViewportView(rowList);
        workingPanel.add(jScrollPane1, BorderLayout.SOUTH);
        workingPanel.getRootPane().setDefaultButton(addMedia);
        bot = new BotMain(args);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        workingPanel = new javax.swing.JPanel();
        mediaAddress = new javax.swing.JTextField();
        addMedia = new javax.swing.JButton();
        clearList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workingPanel.setLayout(new java.awt.BorderLayout());
        workingPanel.add(mediaAddress, java.awt.BorderLayout.CENTER);

        addMedia.setText("Ask");
        addMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMediaActionPerformed(evt);
            }
        });
        workingPanel.add(addMedia, java.awt.BorderLayout.LINE_END);

        clearList.setText("Clear list");
        clearList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearListActionPerformed(evt);
            }
        });
        workingPanel.add(clearList, java.awt.BorderLayout.LINE_START);
        workingPanel.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void addMediaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String urlStr = mediaAddress.getText();
        showRes(urlStr, 1);
        boolean doWrites = true;
        String respond = TestAB.testChat(BotMain.bot, doWrites, MagicBooleans.trace_mode, urlStr);
        //start gif here
        showRes(respond, 2);
        //end here
        
    }                                        

    private void clearListActionPerformed(java.awt.event.ActionEvent evt) {                                          
        DefaultListModel model = (DefaultListModel) rowList.getModel();
        model.removeAllElements();
        links.removeAll(links);
        mediaLinks.removeAll(mediaLinks);
        mediaAddress.setText("");
        rowList.repaint();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	simpleGui.args = args;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simpleGui().setVisible(true);
            }
        });
        URL url = null;
		try {
			url = new URL("http://komarovb.com/gif/gif1.gif");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        Icon icon = new ImageIcon(url);
        JLabel label = new JLabel(icon);

        JFrame f = new JFrame("Animation");
        f.getContentPane().add(label);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.pack();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }
    
    public JMenuBar createMenuBar () {
        JMenuItem menuItem = null;
        JMenuBar menuBar = new JMenuBar();
        JMenu mainMenu = new JMenu("Edit");
        mainMenu.setMnemonic(KeyEvent.VK_E);

        menuItem = new JMenuItem(new DefaultEditorKit.CutAction());
        menuItem.setText("Cut");
        menuItem.setMnemonic(KeyEvent.VK_T);
        mainMenu.add(menuItem);

        menuItem = new JMenuItem(new DefaultEditorKit.CopyAction());
        menuItem.setText("Copy");
        menuItem.setMnemonic(KeyEvent.VK_C);
        mainMenu.add(menuItem);

        menuItem = new JMenuItem(new DefaultEditorKit.PasteAction());
        menuItem.setText("Paste");
        menuItem.setMnemonic(KeyEvent.VK_P);
        mainMenu.add(menuItem);

        menuBar.add(mainMenu);
        return menuBar;
    }
    public void showRes(String urlStr, int type){
    	String sentence = null;
    	if(type == 1 ) sentence = "Human: "+urlStr;
    	else if(type==2) sentence = "YuZaBot: "+urlStr;
    	if(!sentence.equals("")){
            DefaultListModel model = (DefaultListModel) rowList.getModel();
            model.addElement(sentence);
            mediaAddress.setText("");
            rowList.repaint();
    	}
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton addMedia;
    private javax.swing.JButton clearList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mediaAddress;
    private javax.swing.JPanel workingPanel;
    // End of variables declaration                   
}
